SELECT DISTINCT ?item ?goLabel ?p233 ?p2017 ?p8533 ?p235
WHERE 
{
  ?partof wdt:P31 wd:Q2996394.
  ?partof wdt:P686 ?goid.
  ?partof wdt:P279/wdt:P279* wd:Q14914008.
  ?item wdt:P361 ?partof.
  OPTIONAL { ?item wdt:P233 ?p233. }
  OPTIONAL { ?item wdt:P235 ?p235. }
  OPTIONAL { ?item wdt:P2017 ?p2017. }
  OPTIONAL { ?item wdt:P8533 ?p8533. }
  ?partof rdfs:label ?goLabel.
  FILTER (LANG(?goLabel) = 'en')
}

